name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    container:
      image: crystallang/crystal:1.0.0
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install shards
        run: shards install

      - name: Ameba
        run: ./bin/ameba

      - name: Test
        run: crystal spec

      - name: Check the code format
        run: crystal tool format --check ./src ./spec

      - name: Check FIXME/TODO
        run: |
          ! grep --color -Enr --include="*.cr" 'FIXME|TODO' src
          ! grep --color -Enr --include="*.cr" 'FIXME|TODO' spec

      - name: "Check 'spec focus: true'"
        run: |
          ! grep --color -Enr --include="*.cr" 'focus: true do' spec
          ! grep --color -Enr --include="*.cr" 'ftest_' spec

      - name: Check long lines
        run: |
          ! grep --color -Enr --include="*.cr" '.{121}' src
          ! grep --color -Enr --include="*.cr" '.{121}' spec
